version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    env_file: .env
    ports:
     - '8000:8000'
    links:
      - mongo
  mongo:
      container_name: mongo
      image: mongo
      env_file: .env
      volumes:
        - ./data:/data/db
      ports:
        - '27017:27017'

